# Generated by Django 3.2 on 2024-10-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_pedido_estado_pedido'),
        ('compras', '0003_auto_20241017_0028'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='referencia',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='referencia_orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='referencia_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pedido'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
    ]
